## Python Libraries For Data Science

* Data science is the process of deriving knowledge and insights from a huge and diverse set of data through organizing, processing and analysing the data.
* There are nearly 20 python libraries for Data Science. Top five python libraries are
* TensorFlow
* NumPy
* SciPy
* Pandas
* Matplotlib
* In those libraries, Numpy and Pandas are the first choice to the data scientists who are aware of the technologies.

### NumPy:(Numerical Python)

* Numpy is Base N-Dimensional Array Package, is a python library and a fundamental package for scientific computing in Python. It is used to create multidimensional arrays for fast operations. Use the following import conversion.
* import numpy as np

### Introduction to NumPy

* The learning objectives of this section are:
* Understand advantages of vectorised code using     NumPy (over standard python ways)
* Create NumPy arrays
* Convert lists and tuples to NumPy arrays
* Create (initialise) arrays
* Inspect the structure and content of arrays
* Subset, slice, index and iterate through arrays
* Compare computation times in NumPy and standard     Python lists
* There are 3 arrys 1d array,2d array,3d array

In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array([1])

array([1])

In [5]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
type(a)

numpy.ndarray

In [7]:
arr_2d=np.array(([1,2,3],[2,3,4]))
arr_2d

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
type(arr_2d)

numpy.ndarray

In [14]:
arr_3d=np.array([[[1,2],[2,5],[3,6]]])
arr_3d

array([[[1, 2],
        [2, 5],
        [3, 6]]])

In [15]:
l1=[1,2,3,4]
#l1**2
l2=[]
for i in l1:
    l2.append(i**2)
l2    

[1, 4, 9, 16]

In [16]:
%time
res=lambda x:x**2
list(map(res,l1))

Wall time: 0 ns


[1, 4, 9, 16]

In [17]:
s=np.array([1,2,3,4])
s**2

array([ 1,  4,  9, 16], dtype=int32)

In [18]:
s2=np.array([3,4,5,6])
s+s2

array([ 4,  6,  8, 10])

In [19]:
s

array([1, 2, 3, 4])

In [21]:
%time
s/s2

Wall time: 0 ns


array([0.33333333, 0.5       , 0.6       , 0.66666667])

In [25]:
s+s2

array([ 4,  6,  8, 10])

In [27]:
s

array([1, 2, 3, 4])

In [28]:
s[0]

1

In [29]:
s[3]

4

In [30]:
arr_2d

array([[1, 2, 3],
       [2, 3, 4]])

In [32]:
arr_2d[0][0]

1

In [33]:
arr_2d[0][1]

2

In [34]:
range(10)

range(0, 10)

In [35]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a1=np.arange(1,10,2)
print(a1)
print(type(a1))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [38]:
a2=np.array(range(1,10,2))
a2

array([1, 3, 5, 7, 9])

In [40]:
r=range(0,10,2)
type(r)

range

In [43]:
a3=np.linspace(1,10,2) # here 2 represents how many parts it want to divide
a3

array([ 1., 10.])

In [45]:
a3=np.linspace(1,10,10)
a3

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [46]:
range(1.5,10.5)

TypeError: 'float' object cannot be interpreted as an integer

In [31]:
a1=np.arange(1.5,10.5,2)
a1

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [28]:
a2=np.linspace(1.2,90.4,10)
a2

array([ 1.2       , 11.11111111, 21.02222222, 30.93333333, 40.84444444,
       50.75555556, 60.66666667, 70.57777778, 80.48888889, 90.4       ])

In [49]:
a2[0]

1.2

In [50]:
type(a2[0])

numpy.float64

In [52]:
arr_3d

array([[[1, 2],
        [2, 5],
        [3, 6]]])

In [53]:
arr_3d.reshape(2,3)

array([[1, 2, 2],
       [5, 3, 6]])

In [54]:
arr_3d.reshape(4)

ValueError: cannot reshape array of size 6 into shape (4,)

In [55]:
arr_3d.reshape(-1)

array([1, 2, 2, 5, 3, 6])

In [56]:
arr_3d.reshape(3,-1)

array([[1, 2],
       [2, 5],
       [3, 6]])

In [57]:
arr_3d.reshape(-1,3)

array([[1, 2, 2],
       [5, 3, 6]])

In [60]:
a=np.array(([1,2],[3,4],[5,6]))
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
a.itemsize

4

In [62]:
a.ndim

2

In [63]:
a.shape

(3, 2)

In [67]:
help(np.shape)

Help on function shape in module numpy:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    alen
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 2]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (2,)
    >>> a.shape
    (2,)



In [68]:
d=np.arange(1,500,9)
d

array([  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100, 109,
       118, 127, 136, 145, 154, 163, 172, 181, 190, 199, 208, 217, 226,
       235, 244, 253, 262, 271, 280, 289, 298, 307, 316, 325, 334, 343,
       352, 361, 370, 379, 388, 397, 406, 415, 424, 433, 442, 451, 460,
       469, 478, 487, 496])

In [69]:
d[0]

1

In [70]:
d[67]

IndexError: index 67 is out of bounds for axis 0 with size 56

In [71]:
d[56]

IndexError: index 56 is out of bounds for axis 0 with size 56

In [73]:
d[55] # last value

496

In [75]:
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [78]:
np.ones((1,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [84]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [82]:
np.eye(3,3) # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
np.eye(100,100)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [85]:
np.eye((10),dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [86]:
np.eye((10),k=5)

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [87]:
np.eye((10),k=-5)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [55]:
a=[[1,2],[3,4]]
a

[[1, 2], [3, 4]]

In [57]:
a2

array([ 1.2       , 11.11111111, 21.02222222, 30.93333333, 40.84444444,
       50.75555556, 60.66666667, 70.57777778, 80.48888889, 90.4       ])

In [58]:
a2.T

array([ 1.2       , 11.11111111, 21.02222222, 30.93333333, 40.84444444,
       50.75555556, 60.66666667, 70.57777778, 80.48888889, 90.4       ])

In [32]:
a1

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [33]:
a1.T

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [34]:
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Permute the dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : list of ints, optional
        By default, reverse the dimensions, otherwise permute the axes
        according to the values given.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the `axes` keyword argument.
    
    Transposing a 1-D array returns an unchanged view of the original array.
    
    Examples
    --------
    >>> x = np.arange(4).reshape((2,2))
    >>> x
    array([[0, 1],
           [2, 3]])
    
    >>> np.transpose(x)
    array([[0, 2],
           [1, 3]])
    
    >>> x = np.ones((1, 2, 3))
    >>> np.transpose(x, (1, 0, 2)).s

In [59]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [37]:
np.random.random((2,3))

array([[0.24819808, 0.25130553, 0.53374994],
       [0.68979229, 0.62193119, 0.90264067]])

In [38]:
f=np.random.randint(100,500,(25,6))
f

array([[369, 435, 247, 205, 434, 190],
       [171, 423, 234, 472, 218, 343],
       [378, 217, 277, 302, 161, 146],
       [496, 173, 135, 237, 158, 332],
       [334, 496, 250, 432, 310, 479],
       [438, 179, 453, 114, 291, 237],
       [348, 248, 273, 401, 463, 228],
       [462, 188, 496, 342, 423, 268],
       [292, 195, 423, 437, 280, 201],
       [270, 255, 336, 193, 108, 269],
       [186, 375, 451, 385, 292, 150],
       [479, 307, 333, 276, 129, 342],
       [243, 435, 470, 351, 215, 213],
       [245, 463, 307, 493, 372, 345],
       [365, 221, 375, 480, 120, 314],
       [415, 395, 480, 207, 123, 401],
       [276, 176, 336, 453, 218, 343],
       [273, 219, 413, 451, 107, 374],
       [498, 271, 144, 444, 257, 191],
       [388, 158, 265, 350, 480, 294],
       [455, 388, 227, 106, 246, 215],
       [208, 170, 212, 195, 218, 372],
       [275, 265, 373, 308, 332, 350],
       [442, 394, 212, 159, 197, 392],
       [199, 238, 478, 274, 112, 224]])

In [39]:
# we cannot change for one dimension array

In [40]:
f.shape

(25, 6)

In [41]:
f[1]

array([171, 423, 234, 472, 218, 343])

In [42]:
f[1:]

array([[171, 423, 234, 472, 218, 343],
       [378, 217, 277, 302, 161, 146],
       [496, 173, 135, 237, 158, 332],
       [334, 496, 250, 432, 310, 479],
       [438, 179, 453, 114, 291, 237],
       [348, 248, 273, 401, 463, 228],
       [462, 188, 496, 342, 423, 268],
       [292, 195, 423, 437, 280, 201],
       [270, 255, 336, 193, 108, 269],
       [186, 375, 451, 385, 292, 150],
       [479, 307, 333, 276, 129, 342],
       [243, 435, 470, 351, 215, 213],
       [245, 463, 307, 493, 372, 345],
       [365, 221, 375, 480, 120, 314],
       [415, 395, 480, 207, 123, 401],
       [276, 176, 336, 453, 218, 343],
       [273, 219, 413, 451, 107, 374],
       [498, 271, 144, 444, 257, 191],
       [388, 158, 265, 350, 480, 294],
       [455, 388, 227, 106, 246, 215],
       [208, 170, 212, 195, 218, 372],
       [275, 265, 373, 308, 332, 350],
       [442, 394, 212, 159, 197, 392],
       [199, 238, 478, 274, 112, 224]])

In [43]:
f[3]

array([496, 173, 135, 237, 158, 332])

In [44]:
f[[3,4,5]]

array([[496, 173, 135, 237, 158, 332],
       [334, 496, 250, 432, 310, 479],
       [438, 179, 453, 114, 291, 237]])

In [45]:
f[-0]

array([369, 435, 247, 205, 434, 190])

In [46]:
f[2,[2,3]]

array([277, 302])

In [47]:
f[[2,3,4],[2,3,4]]

array([277, 237, 310])

In [60]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [61]:
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [62]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [63]:
np.log(a)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [64]:
np.linalg.det(a)

-2.0000000000000004

In [80]:
np.linalg.inv(a) #when we finding then det not equal to zzero


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [66]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [67]:
a

[[1, 2], [3, 4]]

In [68]:
np.full((1,3),10)

array([[10, 10, 10]])

In [70]:
s=np.array([[[1,2],[9,8]],[[1,2],[7,8]]])
s

array([[[1, 2],
        [9, 8]],

       [[1, 2],
        [7, 8]]])

In [71]:
s.flatten()


array([1, 2, 9, 8, 1, 2, 7, 8])

In [73]:
help(np.tile)

Help on function tile in module numpy:

tile(A, reps)
    Construct an array by repeating A the number of times given by reps.
    
    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.
    
    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.
    
    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
    (1, 1, 2, 2).
    
    Note : Although tile may be used for broadcasting, it is strongly
    recommended to use numpy's broadcasting operations and functions.
    
    Parameters
    ----------
    A : array_like
        The input array.
    reps : array_like
        The number of repetitions of `A`

In [72]:
np.tile(s,2)

array([[[1, 2, 1, 2],
        [9, 8, 9, 8]],

       [[1, 2, 1, 2],
        [7, 8, 7, 8]]])

In [119]:
s

array([1, 2, 3, 4])

In [74]:
s.reshape(2,-1) #function

array([[1, 2, 9, 8],
       [1, 2, 7, 8]])

In [75]:
s.size # Attribute

8

In [76]:
s

array([[[1, 2],
        [9, 8]],

       [[1, 2],
        [7, 8]]])

In [122]:
import math

In [123]:
math.pi # package.attribute

3.141592653589793

In [124]:
math.pow(2,3) #package.function

8.0

In [125]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [79]:
help("math.tan")

Help on built-in function tan in math:

math.tan = tan(x, /)
    Return the tangent of x (measured in radians).



# docs.scipy.org/doc